<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Telimoji</title>
	<meta name="description" content="">
  <link rel="icon" type="image/png" href="img/logo.png">
	<link rel="stylesheet" href="css/style.css">
	
</head>

<body >
	<img src="img/logo.png" id="logo">
	<br>
	<div class="telegram">
		<a href="//telegram.me/imoji_bot">Get for Telegram</a>
	</div>
	<div class="wrapper">
			<strong>1. Using the inline bot on any chat conversation</strong><br><br>
			<a class="name contact-trigger">@imoji_bot </a>
			<i><span class="title">Kanye West</span></i>
			<br><br>
			<img class="imoji" height="150px" src="https://media.imoji.io/601/6013df63-00d2-4943-9f9e-508586b24151/bordered-150.png"></span>
		
	</div>
	
	<div class="wrapper">
			
			<strong>2. Using slash commands with group chats</strong> <br><br>
			<a class="name contact-trigger">/imoji </a>
			<i><span class="title2">hahaha</span></i>
			<br><br>
			<img class="imoji2" src="https://media.imoji.io/f45/f45ab8a2-4ce3-478e-a30d-1364164a4141/bordered-150.png"></span>
			
		
		
	</div>
	
	<div class="footer">
		<a href="https://twitter.com/shivkanthb">@shivkanthb</a>
		<div>Stickers by <a href="https://imoji.io">Imoji.</div>
	</div>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
	<script src="js/plugins.js"></script>
	<script src="js/main.js"></script>
</body>
</html>